ERROR_MESSAGE_Login = "Login failed!"
ERROR_MESSAGE_Register = "Registration failed!"
ERROR_MESSAGE_RegistrationClosed = "The administrator has closed the registration function!"
ERROR_MESSAGE_Logout = "Logout failed!"
ERROR_MESSAGE_Create = "Create failed!"
ERROR_MESSAGE_Edit = "Update failed!"
ERROR_MESSAGE_Get = "Get failed!"
ERROR_MESSAGE_Delete = "Deletion failed!"
ERROR_MESSAGE_Upload = "Upload failed!"
ERROR_MESSAGE_BindData = "The submitted parameters have errors"
ERROR_MESSAGE_Validate = "Validation failed"
ERROR_MESSAGE_PermissionDenied = "Insufficient permissions"
ERROR_MESSAGE_DuplicateUserName = "The current user name already exists!"
ERROR_MESSAGE_DuplicateRoleName = "The current role name already exists!"
ERROR_MESSAGE_ProhibitOperationOfAdministratorUsers = "Prohibit operating administrator users!"
ERROR_MESSAGE_GetToken = "Failed to get token!"
ERROR_MESSAGE_TokenVerificationFailed = "Token verification failed!"
ERROR_MESSAGE_CacheIsNotEnabled = "Cache is not enabled!"
SUCCESS_MESSAGE_Login = "Login successfully!"
SUCCESS_MESSAGE_Register = "Registered successfully!"
SUCCESS_MESSAGE_Logout = "Logout successfully!"
SUCCESS_MESSAGE_Create = "Created successfully!"
SUCCESS_MESSAGE_Edit = "Update successfully!"
SUCCESS_MESSAGE_Get = "Get success!"
SUCCESS_MESSAGE_Delete = "Delete successfully!"
SUCCESS_MESSAGE_Upload = "Uploaded successfully!"